name: Python Style Checker

on: [push]

jobs:
  style-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install PyCodeStyle
        run: pip install pycodestyle
      - name: Run PyCodeStyle
        run: pycodestyle .
